version: "3"

services:
  freshrss_postgresql:
    image: postgres
    restart: unless-stopped
    networks: 
      - rss
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=freshrss
      - POSTGRES_DB=freshrss

  freshrss:
    image: freshrss/freshrss
    restart: unless-stopped
    networks: 
      - traefik
      - rss
    depends_on:
      - freshrss_postgresql
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/5
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss.rule=Host(`rss.tillepille.io`)"
      - "traefik.http.routers.rss.entrypoints=websecure"
      - "traefik.http.routers.rss.tls=true"
      - "traefik.http.routers.rss.tls.certresolver=myresolver"

volumes:
  pgsql_data:
  freshrss_data:
  freshrss_extensions:

networks:
  rss:
  traefik:
    external:
      name: traefik